TP

### 1. Génération des données du problème. <br>
#### a) Générez les données du problème

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cvxpy as cvx
import time
n = 200 # number of examples (you can try with n = 1000 and n = 5000)
p = 2*n # dimensionality of the problem
k = 5 # number of active variables
np.random.seed(0)
X = np.random.randn(n,p) # creating features and normalizing them
X = (X - np.mean(X,axis = 0))/np.std(X,axis = 0)
t = np.arange(0,p)/(p-1); # bulding the variance matrix !
S = np.zeros((p,p))
nn = 0.00001
for i in range(p):
    S[i,:] = np.exp(-(t-t[i])**2/nn);
X = X@(S**.5)
X = X/np.linalg.norm(X,axis=0)
ind = np.random.choice(p, k, replace=False) # generating optimal weights
print(f"index: {ind}")
weights = np.random.randn(k)
weights += 0.1+np.sign(weights) # to get large enough weight
wopt = np.zeros(p)
wopt[ind] = weights
rsnr = 2 # generating output by X@w + noise
z = X[:,ind]@weights
stdnoise = np.std(z)/rsnr
y = z + stdnoise*np.random.randn(n)

index: [309 390  55  82 329]


#### b) Vérifiez que les données ont bien les propriétés attendues

In [ ]:
print(f"Taille de X: {X.shape}")
print(f"Taille de Y: {y.shape}")
print(f"Taille de S: {S.shape}")
print(f"weights: {weights}")

Taille de X: (200, 400)
Taille de Y: (200,)
Taille de S: (400, 400)
weights: [-1.122  1.318 -0.926  2.658 -1.512]


In [16]:
print(f"X:\n {X[:5,:]}")

X:
 [[ 0.145  0.164  0.199 ...  0.143  0.163  0.139]
 [-0.055 -0.039 -0.013 ... -0.088 -0.091 -0.081]
 [ 0.116  0.093  0.051 ... -0.069 -0.095 -0.058]
 [-0.092 -0.057  0.007 ... -0.000 -0.045 -0.067]
 [ 0.007 -0.036 -0.092 ...  0.004 -0.077 -0.116]]


#### c) Calculez l’erreur de généralisation "in sample" de la méthode des moindres carrés

In [ ]:
b_ls = np.linalg.solve(X.T@X,X.T@y)
e_ls = np.sum((X@b_ls-z)**2)
print("Test error for the LS regression: {:0.4f}".format(e_ls))

Test error for the LS regression: 2.7231


#### d) Écrire une fonction Eval_coef(X,z,coeff), qui calcule l’erreur de généralisation "insample"

In [ ]:
def Eval_coef(X,z,coeff):
    e = np.sum((X@coeff - z)**2)
    return e
print(f"Test error for the LS regression (utilisant mon Eval_coef function): {Eval_coef(X,z,b_ls):0.4f}")

Test error for the LS regression (utilisant mon Eval_coef function): 2.7231


### 2. Différentes manières de résoudre le problème du Lasso <br>
#### a) Écrire un programme CVX résolvant, pour λ = 10−3n.

In [51]:
λ = 1e-3*n # le paramètre de régularisation
b = cvx.Variable(p) # le vecteur des coefficients, il sert de variable d'optimisation
obj = cvx.Minimize(0.5*cvx.sum_squares(X@b - y) + λ*cvx.norm(b, 1)) # la fonction objectif à minimiser
prob = cvx.Problem(obj) # le problème d'optimisation
start_time = time.time()
prob.solve(solver=cvx.SCS, eps=1e-5) # résolution du problème avec le solveur SCS
end_time = time.time()

# b) Vérifiez que la solution obtenue est meilleure que celle des moindres carrés
b_ls = np.linalg.solve(X.T@X,X.T@y) # recalcul des coefficients de la régression des moindres carrés
e_ls = np.sum((X@b_ls-z)**2) 
np.set_printoptions(formatter={'float': '{: 0.3f}'.format}) # pour afficher les nombres avec 3 décimales
print("In sample error for the LS regression: {:0.4f}".format(e_ls))

e_la = np.sum((X@b.value-z)**2)
print("In sample error for the Lasso regression: {:0.4f}".format(e_la))

In sample error for the LS regression: 2.7231
In sample error for the Lasso regression: 0.3323


In [52]:
print(f"Alors la methode lasso est bien meilleure que les moindres carrés. avec une erreur de {e_ls-e_la:0.4f} de moins")
print(f"Le temps d'execution est de {end_time - start_time:0.4f} secondes")
print(f"Le nombre de coefficients non nuls est de {np.sum(np.abs(b.value)>1e-4)}")
print(f"Les coefficients non nuls sont aux indices: {np.where(np.abs(b.value)>1e-4)[0]}")
print(f"Les coefficients estimés sont: {b.value[np.where(np.abs(b.value)>1e-4)]}")

Alors la methode lasso est bien meilleure que les moindres carrés. avec une erreur de 2.3908 de moins
Le temps d'execution est de 0.0729 secondes
Le nombre de coefficients non nuls est de 24
Les coefficients non nuls sont aux indices: [ 18  22  42  43  47  55  70  82  93 118 178 190 191 261 275 291 302 309
 310 329 389 390 393 397]
Les coefficients estimés sont: [-0.042  0.081 -0.003 -0.026 -0.018 -0.697 -0.002  2.623 -0.063  0.087
  0.030 -0.192 -0.002 -0.023  0.045 -0.062  0.005 -0.683 -0.018 -1.442
  0.008  1.074  0.036 -0.019]


#### c) Écrire un programme CVX résolvant la formulation suivant de Lasso, avec une valeur <br> de t permettant d’obtenir les mêmes résultats que le problème précédent.

In [58]:
t = np.sum(np.abs(b.value))
b1 = cvx.Variable(p)
obj1 = cvx.Minimize(cvx.sum_squares(X@b1 - y))
c1 = [cvx.norm(b1, 1) <= t]
prob1 = cvx.Problem(obj1, c1)
start_time = time.time()
prob1.solve()
end_time = time.time()
e_la1 = np.sum((X@b1.value - z)**2)
print("In sample error for the Lasso regression (formulation contrainte): {:0.4f}".format(e_la1))

In sample error for the Lasso regression (formulation contrainte): 0.3322


In [59]:
print(f"Avec t = {t:0.4f}, on retrouve bien la même erreur que la formulation precedente avec le lambda")
print("Temps prit pour résoudre le problème Lasso: {:0.4f} secondes".format(end_time - start_time))
print("Le nombre de coefficients non nuls est de {:d}".format(np.sum(np.abs(b1.value)>1e-4)))
print(f"Les coefficients non nuls sont aux indices: {np.where(np.abs(b1.value)>1e-4)[0]}")

Avec t = 7.2826, on retrouve bien la même erreur que la formulation precedente avec le lambda
Temps prit pour résoudre le problème Lasso: 0.2555 secondes
Le nombre de coefficients non nuls est de 24
Les coefficients non nuls sont aux indices: [ 18  22  42  43  47  55  70  82  93 118 178 190 191 261 275 291 302 309
 310 329 389 390 393 397]


#### Écrire un programme CVX résolvant la formulation suivant de Lasso, avec une valeur <br> de ε permettant d’obtenir les mêmes résultats que le problème précédent.

In [ ]:
ε = np.sum((X@b1.value - y)**2)
b2 = cvx.Variable(p)
obj2 = cvx.Minimize(cvx.norm(b2, 1))
c2 = [cvx.sum_squares(X@b2 - y) <= ε]
prob2 = cvx.Problem(obj2, c2)
start_time = time.time()
prob2.solve()
end_time = time.time()
e_la2 = np.sum((X@b2.value - z)**2)
print("In sample error for the Lasso regression (formulation contrainte): {:0.4f}".format(e_la2))
print(f"Temps de calcul pour la formulation pénalisée: {end_time - start_time:0.4f} secondes")


In sample error for the Lasso regression (formulation contrainte): 0.3323
Temps de calcul pour la formulation pénalisée: 0.5737 secondes


In [60]:
### ANALYSE DES RÉSULTATS
# avec lambda = 1e-3*n, t, ε, on retrouve bien les mêmes erreurs pour les 3 formulations du Lasso.
# Le temps de calcul est plus élevé pour la formulation contrainte avec ε.
# Le Lasso est bien meilleur que les moindres carrés en terme d'erreur.
